#!/bin/bash
# Automatic Install for Atom in Ubuntu

echo "Automatic Install for Atom in Ubuntu including NodeJS" \

sudo add-apt-repository ppa:webupd8team/atom \
&& sudo apt-get update \
&& sudo apt-get install nodejs \
&& sudo apt-get install atom \

echo "Thank you for using this little script" \
echo "created by Gerhard" \
